name: pavlok
description: Powered by apps and wearables that enable members to improve their lives.
publish_to: 'none' # 'none' or 'publish'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.1
  get: ^4.6.1
  get_storage: ^2.0.3
  animations: ^2.0.2
  async_builder: ^1.3.1
  touchable: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/